version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

  minio:
    image: minio/minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: tgarchive_dev
      MINIO_ROOT_PASSWORD: tgarchive_dev_password
      MINIO_DOMAIN: minio
      MINIO_REGION_NAME: us-east-1
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mongodb-data:
  minio-data:
