FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm

# Install MinIO client
RUN curl -O https://dl.min.io/client/mc/release/linux-amd64/mc \
    && chmod +x mc \
    && mv mc /usr/local/bin/mc

# Your existing configurations...
